# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.rpc.push_pb2 as push__pb2


class PushServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushInstantly = channel.unary_unary(
                '/rpc.PushService/PushInstantly',
                request_serializer=push__pb2.PushInstantlyRequest.SerializeToString,
                response_deserializer=push__pb2.PushInstantlyResponse.FromString,
                )


class PushServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushInstantly(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PushServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushInstantly': grpc.unary_unary_rpc_method_handler(
                    servicer.PushInstantly,
                    request_deserializer=push__pb2.PushInstantlyRequest.FromString,
                    response_serializer=push__pb2.PushInstantlyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rpc.PushService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PushService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushInstantly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/rpc.PushService/PushInstantly',
            push__pb2.PushInstantlyRequest.SerializeToString,
            push__pb2.PushInstantlyResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
