# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: push.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='push.proto',
  package='rpc',
  syntax='proto3',
  serialized_options=b'Z\005./rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\npush.proto\x12\x03rpc\"f\n\x14PushInstantlyRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t\x12\x13\n\x0breceiver_id\x18\x03 \x01(\x03\x12\x0f\n\x07send_at\x18\x04 \x01(\x03\x12\x11\n\tsender_id\x18\x05 \x01(\x03J\x04\x08\x02\x10\x03\"(\n\x15PushInstantlyResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32W\n\x0bPushService\x12H\n\rPushInstantly\x12\x19.rpc.PushInstantlyRequest\x1a\x1a.rpc.PushInstantlyResponse\"\x00\x42\x07Z\x05./rpcb\x06proto3'
)




_PUSHINSTANTLYREQUEST = _descriptor.Descriptor(
  name='PushInstantlyRequest',
  full_name='rpc.PushInstantlyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='rpc.PushInstantlyRequest.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='receiver_id', full_name='rpc.PushInstantlyRequest.receiver_id', index=1,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='send_at', full_name='rpc.PushInstantlyRequest.send_at', index=2,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender_id', full_name='rpc.PushInstantlyRequest.sender_id', index=3,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=121,
)


_PUSHINSTANTLYRESPONSE = _descriptor.Descriptor(
  name='PushInstantlyResponse',
  full_name='rpc.PushInstantlyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='rpc.PushInstantlyResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=163,
)

DESCRIPTOR.message_types_by_name['PushInstantlyRequest'] = _PUSHINSTANTLYREQUEST
DESCRIPTOR.message_types_by_name['PushInstantlyResponse'] = _PUSHINSTANTLYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PushInstantlyRequest = _reflection.GeneratedProtocolMessageType('PushInstantlyRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUSHINSTANTLYREQUEST,
  '__module__' : 'push_pb2'
  # @@protoc_insertion_point(class_scope:rpc.PushInstantlyRequest)
  })
_sym_db.RegisterMessage(PushInstantlyRequest)

PushInstantlyResponse = _reflection.GeneratedProtocolMessageType('PushInstantlyResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUSHINSTANTLYRESPONSE,
  '__module__' : 'push_pb2'
  # @@protoc_insertion_point(class_scope:rpc.PushInstantlyResponse)
  })
_sym_db.RegisterMessage(PushInstantlyResponse)


DESCRIPTOR._options = None

_PUSHSERVICE = _descriptor.ServiceDescriptor(
  name='PushService',
  full_name='rpc.PushService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=165,
  serialized_end=252,
  methods=[
  _descriptor.MethodDescriptor(
    name='PushInstantly',
    full_name='rpc.PushService.PushInstantly',
    index=0,
    containing_service=None,
    input_type=_PUSHINSTANTLYREQUEST,
    output_type=_PUSHINSTANTLYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PUSHSERVICE)

DESCRIPTOR.services_by_name['PushService'] = _PUSHSERVICE

# @@protoc_insertion_point(module_scope)
